#!/usr/bin/env node
'use strict';
var program = require('commander');
var pkg = require('../package');
program.version( pkg.version, '-v, --version');
program
  .description(pkg.description)
  .parse(process.argv);

// print help with no args
if (program.args.length < 1) {
  program.help();
}

var cli = require('../index.js')();

cli
  .parse(program)
  .then(console.log)
  .catch(console.error)
