#!/usr/bin/env node
'use strict';
var program = require('commander');
var pkg = require('../package');
program.version( pkg.version, '-v, --version');
program
  .description(pkg.description)
  .parse(process.argv);


// print help with no args
if (program.args.length < 1) {
  program.help();
}

require('../index.js')()
